#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Dávať je viac
subtitle: občianske združenie

# Short bio or description (displayed in the header)
description: Dávať je viac je občianske združenie podporujúca žiakov a študentov v hmotnej núdzi. Spájame ľudí, ktorí chcú pomôcť s tými, ktorí pomoc potrebujú.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/davatjeviac/master/img/davatjeviac.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-84224539-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
#url: "http://www.davatjeviac.sk"
url: "https://davatjeviac.github.io"
#url: "http://localhost:4000"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# Email
email: "jgbgzpkbogi@jgbgzpkbogi.yq"
#email: "jgbgzpkbogi@msgor.ius"


# Includes links to social in the footer
social-links:
  facebook: "davat.je.viac"
  twitter: "davatjeviac"
  googleplus: "+DavatJeViac" # anything in your profile username that comes after plus.google.com/


#
# !! You don't need to change any of the configuration flags below !!
#

timezone: Europe/Bratislava
lang: sk

# Permalinks
permalink: /:title/

# Collections
collections:
  bloky:
    output: false
  dobrovolnici:
    output: false
  pribehy:
    output: false
  profily:
    output: false


# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Disable auto-generated ID's for headings
  auto_ids: false
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Compress html files
compress_html:
  clippings: all
  comments: all
  endings: all

# Compress CSS
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - jekyll-serve.app


# CSS file
#css-file: all.css
css-file: main.css
